config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :motorcycles

end

app/models/motorcycle.rb
class Motorcycle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def index
  end

end

app/controllers/motorcycles_controller.rb
class MotorcyclesController < ApplicationController

  def index
    @motorcycles = Motorcycle.all
  end

  def show
    @motorcycle = Motorcycle.find(params[:id])
  end

  def new
    @motorcycle = Motorcycle.new
  end

  def create
    @motorcycle = Motorcycle.new(motorcycle_params)

    respond_to do |format|
      if @motorcycle.save
        format.html { redirect_to @motorcycle, notice: 'Moto was successfully created.' }
        format.json { render :show, status: :created, location: @motorcycle }
      else
        format.html { render :new }
        format.json { render json: @motorcycle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Motorcycle.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to motorcycles_url, notice: 'Moto was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def motorcycle_params
    params.require(:motorcycle).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.haml
.container
  .h2 Index

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Moto Dashboard
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      .page-header
        %h1 Moto Dashboard
      %nav.navbar.navbar-default{:role => "navigation"}
        .navbar-header
          %button.navbar-toggle{"data-target" => "#main-menu", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #main-menu.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Home', root_path
      - flash.each do |severity, message|
        %div{:class => "alert alert-#{severity}"}
          = message
      = yield

app/views/motorcycles/_form.html.haml
= form_for @motorcycle do |f|
  %fieldset
    = f.label :name
    = f.text_field :name
    = f.label :description
    = f.text_field :description
  = f.button :submit, class: "btn btn-primary"

app/views/motorcycles/index.html.haml
- @motorcycles.in_groups_of(4) do |group|
  .row
    - group.compact.each do |motorcycle|
      .col-md-4
        %h4= link_to motorcycle.name, motorcycle
        = motorcycle.description

app/views/motorcycles/new.html.haml
%h1 New Motorcycle
= render "form"

app/views/motorcycles/show.html.haml
%h1= @motorcycle.name
%strong Description:
%p= @motorcycle.description

= link_to "Delete", @motorcycle, data: { confirm: 'Are you sure?' }, method: :delete
= link_to "Back", motorcycles_path